+ sleep 0.1
+ sudo -u tim /home/tim/.i3/save-all.sh
+ for w in {1..10}
+ i3-resurrect save -w 1
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 2
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 3
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 4
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 5
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 6
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 7
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 8
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 9
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ for w in {1..10}
+ i3-resurrect save -w 10
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 62, in save_workspace
    layout.save(workspace, numeric, directory, profile, swallow_criteria)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/layout.py", line 24, in save
    workspace_tree = treeutils.get_workspace_tree(workspace, numeric)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/treeutils.py", line 84, in get_workspace_tree
    subprocess.check_output(shlex.split('i3-msg -t get_tree'))
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '-t', 'get_tree']' returned non-zero exit status 1.
+ i3-msg exit
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
+ pgrep Xorg
+ '[' 1 -eq 0 ']'
+ rmmod nvidia_drm nvidia_modeset nvidia
rmmod: ERROR: Module nvidia is in use by: nvidia_uvm
+ echo -n 0000:01:00.0
+ echo -n 0000:01:00.1
+ echo -n 0000:04:00.0
+ modprobe vfio_pci vfio vfio_iommu_type1 vfio_virqfd
+ :
+ '[' 0 -eq 0 ']'
+ lspci -nnks 01:00.0
+ grep 'Kernel driver in use: nvidia'
+ '[' 1 -eq 0 ']'
+ /home/tim/scripts/update-xorg.sh
+ /usr/bin/win-vm 2
+ systemctl start xlogin@tim
+ ddcutil setvcp 60 1 -b 12 --force-slave-address
DDC communication failed for monitor on I2C bus /dev/i2c-12
+ pgrep polybar
52110
+ '[' 0 -ne 0 ']'
+ sudo -u tim /home/tim/.i3/load-all.sh
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 11, in <module>
    load_entry_point('i3-resurrect==1.4.3', 'console_scripts', 'i3-resurrect')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/i3_resurrect/main.py", line 93, in restore_workspace
    i3 = i3ipc.Connection()
  File "/usr/lib/python3.8/site-packages/i3ipc/connection.py", line 68, in __init__
    raise Exception('Failed to retrieve the i3 or sway IPC socket path')
Exception: Failed to retrieve the i3 or sway IPC socket path
+ DISPLAY=:0
+ xrandr --output HDMI-2 --off --output DP5 --mode 1920x1080 --scale-from 2944x1656
warning: output HDMI-2 not found; ignoring
+ sleep 2
+ DISPLAY=:0
+ feh --bg-scale /home/tim/.i3/lock-cache/resized.png
nc: invalid option -- 'U'
Try `nc --help' for more information.
+ for w in {1..10}
+ i3-resurrect save -w 1
+ for w in {1..10}
+ i3-resurrect save -w 2
+ for w in {1..10}
+ i3-resurrect save -w 3
+ for w in {1..10}
+ i3-resurrect save -w 4
+ for w in {1..10}
+ i3-resurrect save -w 5
+ for w in {1..10}
+ i3-resurrect save -w 6
+ for w in {1..10}
+ i3-resurrect save -w 7
+ for w in {1..10}
+ i3-resurrect save -w 8
+ for w in {1..10}
+ i3-resurrect save -w 9
+ for w in {1..10}
+ i3-resurrect save -w 10
DDC communication failed for monitor on I2C bus /dev/i2c-12
modprobe: ERROR: could not remove 'vfio': No such file or directory
700804
